In [5]:
##Basic Array Operaions
#1.Create a 3x3 array with random integers, calculate sum, mean, and standard deviation
import numpy as np
arr1 = np.random.randint(0, 11, (3, 3))
print("Array:\n", arr1)
print("Sum:", np.sum(arr1))
print("Mean:", np.mean(arr1))
print("Standard Deviation:", np.std(arr1))

Array:
 [[ 2  3  6]
 [ 0 10  7]
 [ 8  7  2]]
Sum: 45
Mean: 5.0
Standard Deviation: 3.1622776601683795


In [6]:
#2.Create a 1D array of 10 elements and compute the cumulative sum.arr2 = np.random.randint(1, 11, 10)
print("Array:", arr2)
print("Cumulative Sum:", np.cumsum(arr2))

Array: [8 3 2 4 9 7 2 6 4 5]
Cumulative Sum: [ 8 11 13 17 26 33 35 41 45 50]


In [7]:
#3.Generate two 2x3 arrays and perform element-wise operations.arr3 = np.random.randint(1, 11, (2, 3))
arr4 = np.random.randint(1, 11, (2, 3))
print("Array 1:\n", arr3)
print("Array 2:\n", arr4)
print("Addition:\n", arr3 + arr4)
print("Subtraction:\n", arr3 - arr4)
print("Multiplication:\n", arr3 * arr4)
print("Division:\n", arr3 / arr4)

Array 1:
 [[1 3 8]
 [4 6 7]]
Array 2:
 [[4 7 4]
 [4 8 4]]
Addition:
 [[ 5 10 12]
 [ 8 14 11]]
Subtraction:
 [[-3 -4  4]
 [ 0 -2  3]]
Multiplication:
 [[ 4 21 32]
 [16 48 28]]
Division:
 [[0.25       0.42857143 2.        ]
 [1.         0.75       1.75      ]]


In [8]:
#4.Create a 4x4 identity matrix.
identity_matrix = np.eye(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [9]:
#5.Divide array by 5 using broadcasting.
a = np.array([5, 10, 15, 20, 25])
print(a / 5)

[1. 2. 3. 4. 5.]


In [10]:
##Array Manipulation
#6.Reshape a 1D array of 12 elements into a 3x4 matrix.
arr6 = np.arange(12)
reshaped_arr = arr6.reshape(3, 4)
print(reshaped_arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [11]:
#7.Flatten a 3x3 matrix into a 1D array.
arr7 = np.random.randint(1, 11, (3, 3))
print("Original Matrix:\n", arr7)
print("Flattened Array:", arr7.flatten())

Original Matrix:
 [[ 5  7  4]
 [ 6  2 10]
 [ 7  9  7]]
Flattened Array: [ 5  7  4  6  2 10  7  9  7]


In [12]:
#8.Stack two 3x3 matrices horizontally and vertically.
arr8_1 = np.random.randint(1, 11, (3, 3))
arr8_2 = np.random.randint(1, 11, (3, 3))
print("Horizontal Stack:\n", np.hstack((arr8_1, arr8_2)))
print("Vertical Stack:\n", np.vstack((arr8_1, arr8_2)))

Horizontal Stack:
 [[ 2  1  4  5  3  3]
 [ 8  5  3 10  2  9]
 [ 9 10 10  1 10  5]]
Vertical Stack:
 [[ 2  1  4]
 [ 8  5  3]
 [ 9 10 10]
 [ 5  3  3]
 [10  2  9]
 [ 1 10  5]]


In [43]:
#9.Concatenate two arrays of different sizes along a new axis.
arr9_1 = np.random.randint(1, 11, 3)
arr9_2 = np.random.randint(1, 11, 5)
# Concatenate along axis=0 to stack vertically,
# since the arrays have different lengths but can be stacked on top of each other
concatenated_arr = np.concatenate((arr9_1[:, np.newaxis], arr9_2[:, np.newaxis]), axis=0)
print(concatenated_arr)

[[8]
 [4]
 [8]
 [5]
 [8]
 [3]
 [8]
 [8]]


In [15]:
#10.Transpose a 3x2 matrix and reshape it to have 3 rows and 2 columns.
arr10 = np.random.randint(1, 11, (3, 2))
transposed_arr = arr10.T
reshaped_arr = transposed_arr.reshape(3, 2)
print(reshaped_arr)

[[ 1  8]
 [ 2 10]
 [ 4  5]]


In [16]:
##Indexing and Slicing
#11.Extract elements at positions 2 to 10 with a step of 2.
arr11 = np.arange(15)
print(arr11[2:11:2])

[ 2  4  6  8 10]


In [17]:
#12.Extract sub-matrix from 5x5 matrix.
arr12 = np.random.randint(1, 11, (5, 5))
print("Original Matrix:\n", arr12)
print("Sub-matrix:\n", arr12[1:4, 2:5])

Original Matrix:
 [[ 1  3  3  9  1]
 [ 1  3  2  9  6]
 [10  9  4  3  4]
 [ 3  2  6  6  9]
 [ 8  6  6  9  1]]
Sub-matrix:
 [[2 9 6]
 [4 3 4]
 [6 6 9]]


In [18]:
#13.Replace all elements greater than 10 with 10.
arr13 = np.random.randint(5, 20, 10)
arr13[arr13 > 10] = 10
print(arr13)

[10 10 10  9 10 10  8  9 10 10]


In [19]:
#14.Fancy indexing to select specific elements.
arr14 = np.arange(10)
print(arr14[[0, 2, 4, 6]])

[0 2 4 6]


In [20]:
#15.Reverse a 1D array using slicing.
arr15 = np.random.randint(1, 11, 10)
print("Reversed Array:", arr15[::-1])

Reversed Array: [6 3 5 4 5 6 5 1 4 7]


In [21]:
##Broadcasting
#16.Add a 1x3 array to each row of a 3x3 matrix.
arr16 = np.random.randint(1, 11, (3, 3))
arr16_row = np.array([1, 2, 3])
print(arr16 + arr16_row)

[[ 4  5 12]
 [ 7 10 11]
 [ 7  5  4]]


In [22]:
#17.Multiply a 1D array of 5 elements by a scalar.
arr17 = np.random.randint(1, 11, 5)
print(arr17 * 5)

[10 40 20  5 45]


In [23]:
#18.Sutract a 3x1 column vector from a 3x3 matrix.
arr18 = np.random.randint(1, 11, (3, 3))
col_vec = np.array([[1], [2], [3]])
print(arr18 - col_vec)

[[9 3 1]
 [2 1 1]
 [1 7 0]]


In [24]:
#19.Add a scalar to a 3D array.
arr19 = np.random.randint(1, 11, (2, 2, 2))
print(arr19 + 5)

[[[ 9  7]
  [ 6 15]]

 [[13 11]
  [10 11]]]


In [25]:
#20.Add two arrays of shapes (4, 1) and (1, 5).
arr20_1 = np.random.randint(1, 11, (4, 1))
arr20_2 = np.random.randint(1, 11, (1, 5))
print(arr20_1 + arr20_2)

[[ 8 10  6  9 11]
 [12 14 10 13 15]
 [ 7  9  5  8 10]
 [ 9 11  7 10 12]]


In [26]:
##Vectorized Operations
#21.Compute square root of each element in a 2D array.
arr21 = np.random.randint(1, 11, (3, 3))
print(np.sqrt(arr21))

[[2.82842712 1.41421356 1.41421356]
 [3.16227766 1.41421356 3.16227766]
 [2.23606798 3.16227766 1.        ]]


In [27]:
#22.Calculate dot product of two 1D arrays.
arr22_1 = np.random.randint(1, 11, 5)
arr22_2 = np.random.randint(1, 11, 5)
print(np.dot(arr22_1, arr22_2))

89


In [28]:
#23.Element-wise comparison of two arrays.
arr23_1 = np.random.randint(1, 11, 5)
arr23_2 = np.random.randint(1, 11, 5)
print(arr23_1 > arr23_2)

[False  True  True False False]


In [29]:
#24.Double the value of each element in a 2D array.
arr24 = np.random.randint(1, 11, (3, 3))
print(arr24 * 2)

[[20  4 14]
 [10 16 14]
 [ 4  6  4]]


In [30]:
#25.Sum of all even numbers in a 1D array of 100 integers.
arr25 = np.random.randint(1, 101, 100)
print(np.sum(arr25[arr25 % 2 == 0]))

2706


In [31]:
##Linear Alzebra
#26.Create a 3x3 matrix and find its determinant.
arr26 = np.random.randint(1, 11, (3, 3))
print("Matrix:\n", arr26)
print("Determinant:", np.linalg.det(arr26))

Matrix:
 [[7 4 6]
 [4 3 6]
 [2 3 8]]
Determinant: -1.9999999999999931


In [32]:
#27.Compute the inverse of a 2x2 matrix and verify.
arr27 = np.random.randint(1, 11, (2, 2))
inverse_arr27 = np.linalg.inv(arr27)
identity_check = np.dot(arr27, inverse_arr27)
print("Original Matrix:\n", arr27)
print("Inverse:\n", inverse_arr27)
print("Identity Check:\n", np.round(identity_check))

Original Matrix:
 [[ 5  2]
 [10  6]]
Inverse:
 [[ 0.6 -0.2]
 [-1.   0.5]]
Identity Check:
 [[1. 0.]
 [0. 1.]]


In [33]:
#28.Calculate eigenvalues and eigenvectors of a 2x2 matrix.
arr28 = np.random.randint(1, 11, (2, 2))
eigenvalues, eigenvectors = np.linalg.eig(arr28)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues: [-1.63324958 11.63324958]
Eigenvectors:
 [[-0.93596603 -0.54985995]
 [ 0.35209031 -0.83525687]]


In [41]:
#29.Solve the system of linear equations 2x + 3y = 5 and 4x + 6y = 10.
A= np.array([[2, 3], [4, 6]])
B = np.array([5, 10])
try:
    # The following two lines were not indented properly
    solution = np.linalg.solve(A, B)
    print("Solution:", solution)
except np.linalg.LinAlgError:
    # This line was also not indented properly
    print("No unique solution, system is singular.")

No unique solution, system is singular.


In [42]:
#30.Perform Singular Value Decomposition (SVD) and reconstruct matrix.
arr30 = np.random.randint(1, 11, (3, 3))
U, S, Vt = np.linalg.svd(arr30)
S_matrix = np.diag(S)
reconstructed_matrix = np.dot(U, np.dot(S_matrix, Vt))
print("Original Matrix:\n", arr30)
print("Reconstructed Matrix:\n", np.round(reconstructed_matrix))

Original Matrix:
 [[6 3 9]
 [1 5 2]
 [4 4 9]]
Reconstructed Matrix:
 [[6. 3. 9.]
 [1. 5. 2.]
 [4. 4. 9.]]
